name: Sync Gcal to Notion
on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch:

jobs:
    sync:
        name: Sync Google Calendar Events to Notion
        runs-on: ubuntu-latest
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
            GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
            NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
            NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:            
                python-version: '3.11'
    
            - name: Install dependencies
              run: |
                pip install -r requirements.txt

            - name : Restore credentials and tokens
              run: |
                echo "$GOOGLE_CREDENTIALS" | base64 --decode > credentials.json
                echo "$GOOGLE_TOKEN" | base64 --decode > token.json
    
            - name: Run script
              run: |
                python sync_gcal_to_notion.py  